### ISSUE TITLE
UI service error

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#1324] opened 2018-06-08 03:18 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
why?
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0beta
- Which company or project?
madecare
- What happen?
![image](https://user-images.githubusercontent.com/29936988/41137357-5946f5da-6b0d-11e8-8019-9e68f372bfd5.png)
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Browse requests and returns
[request.txt](https://github.com/apache/incubator-skywalking/files/2082799/request.txt)
[response.txt](https://github.com/apache/incubator-skywalking/files/2082801/response.txt)
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-06-08 03:20
@hanahmily Please check the data, whether include some invalid data.

**Comment by hanahmily** [comment] 2018-06-08 03:34
Duplicate of https://github.com/apache/incubator-skywalking-ui/issues/141

**Closed by hanahmily** 2018-06-08 03:34 UTC

**Comment by wu-sheng** [comment] 2018-06-08 05:56
Haha, too many duplicate issue.
