### ISSUE TITLE
oap can't review data after  about 8 hours  in 6.0.0-beta-SNAPSHOT

### ISSUE THREAD

**Issue by a198720** [apache/incubator-skywalking#1991] opened 2018-12-02 14:24 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
     I am running skywalking in docker,the storate use es, Everything works fine at the beginning, I can collect all the monitoring data. But after about 8 hours, I can't collect all the data.  The final solution is to restart oap. and then it is back to normal. But I don't know why this happens ?  Can you help me solve this problem?
[skywalking-oap-server.log](https://github.com/apache/incubator-skywalking/files/2637001/skywalking-oap-server.log)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by qdlake** [comment] 2018-12-04 09:53
6.0.0-alpha , agent add -Dskywalking.agent.service_name=spring-boot-demo, skywalking ui dashboard can not display service, service‘s ’count is 0. Endpoint and DB & Cache display count.

**Comment by wu-sheng** [comment] 2018-12-04 10:10
> 6.0.0-alpha , agent add -Dskywalking.agent.service_name=spring-boot-demo, skywalking ui dashboard can not display service, service‘s ’count is 0. Endpoint and DB & Cache display count.

@qdlake Your agent mechanic OS time or time zone is not right. Your issue doesn't relate to this.
We have no clue what is happening in this issue.

**Comment by a198720** [comment] 2018-12-06 05:31
this time, I deploy oap with a different configuration. first I use h2 as the storage. after 8 hours , It is normal.
second, I use es as the storage, after 8 hours , It is normal. third,I use es as the storage, and config the namespace in system environment with SW_STORAGE_ES_NAMESPACE,after 8 hours ,It no longer collects a bit of data. So I can only restart the oap component to make it back to normal.

**Comment by a198720** [comment] 2018-12-06 05:32
@wu-sheng @peng-yongsheng  Can you give some ideas to consider what is the trigger?

**Comment by wu-sheng** [comment] 2018-12-06 06:00
If the namespace, there is a bug fixed in beta milestone, the delete mechanism doesn't work right. So, based on the things you provided, it may be caused by ElasticSearch overload. That is the only thing I could relate with.

**Closed by wu-sheng** 2018-12-06 06:00 UTC
Labels: collector, question
