### ISSUE TITLE
5.0.0-alpha grpc server CallServerInterceptor some times has null exception

### ISSUE THREAD

**Issue by wangmh** [apache/incubator-skywalking#1044] opened 2018-04-07 13:43 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [# ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS and JRE?
  grpc 1.8  and skywalking 5.0.0 alpha  mac jdk 1.8
- Which company or project?
  http://hualala.com/
- What happen?

 one grpc client, call two grpc servers. then both servers will show null exception some times.

> 四月 07, 2018 2:55:18 下午 io.grpc.internal.SerializingExecutor run
> 严重: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@5cd81a9e
> java.lang.NullPointerException
> 	at org.apache.skywalking.apm.agent.core.context.ContextManager.activeSpan(ContextManager.java:163)
> 	at org.apache.skywalking.apm.agent.core.context.ContextManager.stopSpan(ContextManager.java:167)
> 	at org.apache.skywalking.apm.plugin.grpc.v1.CallServerInterceptor$ServerCallListener.onComplete(CallServerInterceptor.java:97)
> 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:278)
> 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:679)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by wu-sheng** [comment] 2018-04-07 13:50
@wangmh What is your way of using gRPC streaming? From the stack, I just know there is really no active span. Maybe bug, or maybe across thread.

**Comment by wangmh** [comment] 2018-04-07 13:56
i just test skywalking useing  grpc self's example code "Greeter code"
https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java

**Comment by ascrutae** [comment] 2018-04-08 14:39
@wangmh  I cannot reproduce this issue by using the demo that your posted me.  Can you post me the reproduce step?

**Comment by wangmh** [comment] 2018-04-09 23:59
I can reproduce in my mac pro notebook,  but  it  has not   reproduce  on my  linux server util now . 
But in our grpc products, we  have found  that we used thread local in a wrong way.  

[grpc cross thread.pdf](https://github.com/apache/incubator-skywalking/files/1892337/grpc.cross.thread.pdf)

**Comment by wu-sheng** [comment] 2018-04-10 00:36
@wangmh Thanks for sharing with us this document. Then I assume this is not a SkyWalking bug, is that right? 

But, I have to say, auto instrumentation agent is hard to find out this situation.

**Comment by wangmh** [comment] 2018-04-10 01:46
I think brave'TracingServerInterceptor can avoid "cross thread" situation.
https://github.com/openzipkin/brave/blob/master/instrumentation/grpc/src/main/java/brave/grpc/TracingServerInterceptor.java

I will read SkyWalking code deeply to find if it is a SkyWalking bug .

**Comment by wu-sheng** [comment] 2018-04-10 01:57
Sure, take your time. I tagged this question as `question`. And some design of our core has more restrictions than Zipkin ( FYI @adriancole ) , because manual instrumentation has more freedom, and you control more.

You can consider to optimize our instrumentation way.

**Comment by wu-sheng** [comment] 2018-04-25 01:07
Closing this because this issue has no updates in 15 days.

**Comment by wu-sheng** [comment] 2018-05-10 08:40
Fixed in #1190

**Closed by wu-sheng** 2018-05-10 08:40 UTC
Labels: agent, question
