### ISSUE TITLE
 Tracing order shows error when I use hystrix before dubbo 

### ISSUE THREAD

**Issue by windywang** [apache/incubator-skywalking#1423] opened 2018-07-03 08:53 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [* ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
when I use hystrix  before Dubbo,call sequence randomly displays errors。
Sometimes the order of hystrix is ​​first, sometimes the order of the dubbo provider is first.
It is also recommended that the fonts should not use white.Because  when the call time is very short, the word cannot be seen.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by peng-yongsheng** [comment] 2018-07-03 08:56
Sample data
```
{
	"data": {
		"queryTrace": {
			"spans": [{
				"traceId": "8.89.15306041834574351",
				"segmentId": "8.89.15306041834574350",
				"spanId": 0,
				"parentSpanId": -1,
				"refs": [],
				"applicationCode": "trace_provider_b",
				"startTime": 1530604183457,
				"endTime": 1530604183458,
				"operationName": "/demo2",
				"type": "Entry",
				"peer": "",
				"component": "SpringMVC",
				"isError": false,
				"layer": "Http",
				"tags": [{
					"key": "url",
					"value": "http://10.253.162.194:8083/demo2"
				}, {
					"key": "http.method",
					"value": "GET"
				}],
				"logs": []
			}, {
				"traceId": "8.89.15306041834574351",
				"segmentId": "8.89.15306041834574350",
				"spanId": 1,
				"parentSpanId": 0,
				"refs": [],
				"applicationCode": "trace_provider_b",
				"startTime": 1530604183457,
				"endTime": 1530604183458,
				"operationName": "com.bangdao.plat.trace_test_a.biz.facade.HelloService.getHello(HelloReq)",
				"type": "Exit",
				"peer": "10.253.162.194:20892",
				"component": "Dubbo",
				"isError": false,
				"layer": "RPCFramework",
				"tags": [{
					"key": "url",
					"value": "dubbo://10.253.162.194:20892/com.bangdao.plat.trace_test_a.biz.facade.HelloService.getHello(HelloReq)"
				}],
				"logs": []
			}, {
				"traceId": "8.89.15306041834574351",
				"segmentId": "12.336.15306041834583034",
				"spanId": 0,
				"parentSpanId": -1,
				"refs": [{
					"traceId": "8.89.15306041834574351",
					"parentSegmentId": "8.89.15306041834574350",
					"parentSpanId": 1,
					"type": "CROSS_PROCESS"
				}],
				"applicationCode": "trace_provider_a",
				"startTime": 1530604183458,
				"endTime": 1530604183458,
				"operationName": "com.bangdao.plat.trace_test_a.biz.facade.HelloService.getHello(HelloReq)",
				"type": "Entry",
				"peer": "",
				"component": "Dubbo",
				"isError": false,
				"layer": "RPCFramework",
				"tags": [{
					"key": "url",
					"value": "dubbo://10.253.162.194:20892/com.bangdao.plat.trace_test_a.biz.facade.HelloService.getHello(HelloReq)"
				}],
				"logs": []
			}, {
				"traceId": "8.89.15306041834574351",
				"segmentId": "8.114.15306041834577602",
				"spanId": 0,
				"parentSpanId": -1,
				"refs": [{
					"traceId": "8.89.15306041834574351",
					"parentSegmentId": "8.89.15306041834574350",
					"parentSpanId": 1,
					"type": "CROSS_THREAD"
				}],
				"applicationCode": "trace_provider_b",
				"startTime": 1530604183457,
				"endTime": 1530604183458,
				"operationName": "Hystrix/com.bangdao.plat.trace_test_a.biz.facade.HelloService.getHello/Execution",
				"type": "Local",
				"peer": "",
				"component": "Hystrix",
				"isError": false,
				"layer": "Unknown",
				"tags": [],
				"logs": []
			}]
		}
	}
}
```

**Comment by peng-yongsheng** [comment] 2018-07-03 09:19
@wu-sheng @hanahmily @ascrutae 
As the sample data above, there are two segments with the id, 12.336.15306041834583034 and 8.114.15306041834577602. Those two segments had the same parent. Thus, trace builder cannot distinguish which one is first.

**Comment by wu-sheng** [comment] 2018-07-03 16:19
@windywang Could you provide more details about your case? Does `trace_provider_b` use the Hytrix with a callback? Or as a retry mechanism?

Or could you provide us this demo?

@peng-yongsheng Hystrix did a very tricky work. Too many threads in it.

**Comment by windywang** [comment] 2018-07-04 00:57
@wu-sheng   
dubbo filter:  
@Activate(group = Constants.CONSUMER, before = "future")
public class HystrixFilter implements Filter {
    private static final Logger logger = LoggerFactory.getLogger(HystrixFilter.class);


    private ThreadPoolConfig  threadPoolConfig;
    private DubboHystrixCommandConfig dubboHystrixCommandConfig;

    public void setThreadPoolConfig(ThreadPoolConfig threadPoolConfig) {
        this.threadPoolConfig = threadPoolConfig;
    }

    public void setDubboHystrixCommandConfig(DubboHystrixCommandConfig dubboHystrixCommandConfig) {
        this.dubboHystrixCommandConfig = dubboHystrixCommandConfig;
    }

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        URL url = invoker.getUrl();
        String methodName = invocation.getMethodName();
        String interfaceName = invoker.getInterface().getName();
        HystrixCommand.Setter setter = HystrixCommandSetterFactory.create(interfaceName, methodName, url, threadPoolConfig, dubboHystrixCommandConfig);
        String fallback = url.getMethodParameter(methodName, "fallback");
        DubboCommand command = new DubboCommand(setter, invoker, invocation, fallback,RpcContext.getContext());
        Result result = command.execute();
        return result;
    }
}


DubooCommand :

public class DubboCommand extends HystrixCommand<Result> {


    private Invoker<?> invoker;
    private Invocation invocation;
    private String fallbackName;
    private RpcContext rpcContext;

    public DubboCommand(Setter setter, Invoker<?> invoker, Invocation invocation, String fallbackName, RpcContext rpcContext) {
        super(setter);
        this.invoker = invoker;
        this.invocation = invocation;
        this.fallbackName = fallbackName;
        this.rpcContext = rpcContext;
    }

    @Override
    protected Result run() throws Exception {
        RpcContext.getContext().setAttachments(rpcContext.getAttachments());
        Result result = invoker.invoke(invocation);
        if (result.hasException()) {
            throw (Exception) result.getException();
        }
        return result;
    }

**Comment by wu-sheng** [comment] 2018-07-04 01:21
@ascrutae Please try to do this.

**Comment by ascrutae** [comment] 2018-07-18 21:50
What is the dubbo version you used?

**Comment by windywang** [comment] 2018-07-19 02:55
@ascrutae   dubbo. 2.6.0.  hystrix. 1.5.12

**Comment by ascrutae** [comment] 2018-08-23 21:08
Cannot reproduce this produce this problem with the latest code. 

BTW, I found that the trace context cannot propagate. because the dubbo plugin propagate trace context through the [RPCContext](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/org/apache/skywalking/apm/plugin/dubbo/DubboInterceptor.java#L59).

> RpcContext.getContext().setAttachments(rpcContext.getAttachments());

The `RPCContext.getAttachments` method  get `attachments` value from threadLocal. and Hystrix will execute `run` method in an new thread, **Not in main thread**, so current Hystrix filter cannot propagate the trace context. To resolve this problem. You should pass the `attachments` arguments. Not `RPCContext`

**Comment by ascrutae** [comment] 2018-08-24 00:11
Close this issue. and this issue should fix in `HystrixFilter`, Not dubbo plugin.

**Closed by ascrutae** 2018-08-24 00:11 UTC
Labels: question, wontfix
