### ISSUE TITLE
Failed to execute 'drawImage' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1853] opened 2018-10-31 10:28 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0.RC   Centos6.9

- Which company or project?

- What happen?
In "Application" tab, sometimes it will hit following error. It will cause the "appliation map" can't  be scaling, and when change to another app the application map can't be changed. This issue will happened occasionally.

error:
1.df947761.async.js:1 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at j.r.safeDrawImage (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1499607)
    at j.r.drawInscribedImage (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1501277)
    at F (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1507558)
    at j.i.drawNode (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1508714)
    at j.i.drawElement (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1494518)
    at u.c.getElement (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1484648)
    at j.i.drawCachedElement (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1494707)
    at j.i.drawCachedElements (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1495008)
    at j.i.drawLayeredElements (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1495365)
    at j.r.render (http://skywalking.corp.tujia.com/1.df947761.async.js:1:1515104)

api:
/api/application

request:
{"variables":{"duration":{"start":"2018-10-31 1807","end":"2018-10-31 1822","step":"MINUTE"},"applicationId":"-1"},"query":"      query Application($applicationId: ID!, $duration: Duration!) {        getSlowService(applicationId: $applicationId, duration: $duration, topN: 10) {          service {            key: id            label: name            applicationId            applicationName          }          value: avgResponseTime        }        getServerThroughput(applicationId: $applicationId, duration: $duration, topN: 999999) {          key: id          osName          host          pid          ipv4          value: cpm        }        getApplicationTopology(applicationId: $applicationId, duration: $duration) {          nodes {            id            name            type            ... on ApplicationNode {              sla              cpm              avgResponseTime              apdex              isAlarm              numOfServer              numOfServerAlarm              numOfServiceAlarm            }          }          calls {            source            target            isAlert            callType            cpm            avgResponseTime          }        }      }    "}

response:
{"data":{"getSlowService":[{"service":{"key":"12","label":"/bingo/app/portal/getminpricehouse","applicationId":"-1","applicationName":"tns-portal-app"},"value":314},{"service":{"key":"-13","label":"/bingo/app/portal/getpalacehouse","applicationId":"-1","applicationName":"tns-portal-app"},"value":271},{"service":{"key":"-30","label":"/tmsv4/SearchUnitFull","applicationId":"-1","applicationName":"tns-portal-app"},"value":262},{"service":{"key":"-6","label":"/bingo/app/search/searchhouse","applicationId":"-1","applicationName":"tns-portal-app"},"value":257},{"service":{"key":"-22","label":"/bingo/app/search/searchhousebyunitproductfilters","applicationId":"-1","applicationName":"tns-portal-app"},"value":230},{"service":{"key":"26","label":"/bingo/app/house/getproductdeposit","applicationId":"-1","applicationName":"tns-portal-app"},"value":213},{"service":{"key":"15","label":"/bingo/app/portal/getrecommendlandmark","applicationId":"-1","applicationName":"tns-portal-app"},"value":153},{"service":{"key":"37","label":"/tmsv4/getHotel","applicationId":"-1","applicationName":"tns-portal-app"},"value":130},{"service":{"key":"-25","label":"/appunit/getSimilarUnitIdList","applicationId":"-1","applicationName":"tns-portal-app"},"value":127},{"service":{"key":"-34","label":"/AppPortal/getspecialsalechannel","applicationId":"-1","applicationName":"tns-portal-app"},"value":119}],"getServerThroughput":[{"key":"182","osName":"Linux","host":"l-tnsapp-web1.rd.cn1","pid":29520,"ipv4":["175.32.39.85"],"value":13},{"key":"186","osName":"Linux","host":"l-tnsapp-web5.rd.cn1","pid":25069,"ipv4":["175.32.30.55"],"value":13},{"key":"189","osName":"Linux","host":"l-tnsapp-web1.rd.cn2","pid":32437,"ipv4":["175.32.86.101"],"value":12},{"key":"184","osName":"Linux","host":"l-tnsapp-web3.rd.cn1","pid":12328,"ipv4":["175.32.39.87"],"value":11},{"key":"185","osName":"Linux","host":"l-tnsapp-web4.rd.cn1","pid":10047,"ipv4":["175.32.39.88"],"value":11},{"key":"183","osName":"Linux","host":"l-tnsapp-web2.rd.cn1","pid":27567,"ipv4":["175.32.39.86"],"value":10},{"key":"187","osName":"Linux","host":"l-tnsapp-web7.rd.cn1","pid":16639,"ipv4":["175.32.30.57"],"value":10},{"key":"188","osName":"Linux","host":"l-tnsapp-web8.rd.cn1","pid":783,"ipv4":["175.32.30.58"],"value":10},{"key":"190","osName":"Linux","host":"l-tnsapp-web2.rd.cn2","pid":32596,"ipv4":["175.32.86.102"],"value":10}],"getApplicationTopology":{"nodes":[{"id":"-126","name":"tns-portal-bridge","type":"rocketMQ-consumer","sla":100,"cpm":64,"avgResponseTime":13,"apdex":100,"isAlarm":false,"numOfServer":5,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"-1","name":"tns-portal-app","type":"SpringMVC","sla":100,"cpm":83,"avgResponseTime":80,"apdex":100,"isAlarm":false,"numOfServer":9,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"53","name":"tujia-member","type":"Tomcat","sla":100,"cpm":3455,"avgResponseTime":2,"apdex":100,"isAlarm":false,"numOfServer":1,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"62","name":"tns_promotion","type":"Tomcat","sla":100,"cpm":1438,"avgResponseTime":11,"apdex":100,"isAlarm":false,"numOfServer":1,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"104","name":"cms-provider","type":"rocketMQ-consumer","sla":100,"cpm":6,"avgResponseTime":37,"apdex":100,"isAlarm":false,"numOfServer":4,"numOfServerAlarm":0,"numOfServiceAlarm":0},{"id":"-32","name":"175.32.86.169:12345","type":"Dubbo"},{"id":"-21","name":"175.32.35.71:20081","type":"Dubbo"},{"id":"-20","name":"175.32.39.40:20086","type":"Dubbo"},{"id":"-18","name":"175.32.30.21:20086","type":"Dubbo"},{"id":"-17","name":"175.32.39.111:20086","type":"Dubbo"},{"id":"-15","name":"175.32.30.20:20086","type":"Dubbo"},{"id":"-12","name":"175.32.35.69:20081","type":"Dubbo"},{"id":"-11","name":"175.32.35.72:20081","type":"Dubbo"},{"id":"-9","name":"175.32.30.95:12345","type":"Dubbo"},{"id":"-8","name":"175.32.35.78:12345","type":"Dubbo"},{"id":"-7","name":"175.32.39.230:27020","type":"Redis"},{"id":"-5","name":"customerservice-sync.wcf.corp.tujia.com:80","type":"HttpClient"},{"id":"-4","name":"service6003-sync.wcf.corp.tujia.com:80","type":"HttpClient"},{"id":"-3","name":"175.32.38.50:20086","type":"Dubbo"},{"id":"-2","name":"t-search-support.corp.tujia.com:80","type":"HttpClient"},{"id":"2","name":"175.32.35.77:12345","type":"Dubbo"},{"id":"3","name":"t-unitfeaturetag.corp.tujia.com:80","type":"HttpClient"},{"id":"4","name":"t-unitsearch.corp.tujia.com:80","type":"HttpClient"},{"id":"5","name":"175.32.35.70:20081","type":"Dubbo"},{"id":"7","name":"175.32.39.230:7020","type":"Redis"},{"id":"8","name":"175.32.120.11:7020","type":"Redis"},{"id":"10","name":"175.32.30.88:20880","type":"Dubbo"},{"id":"11","name":"175.32.38.49:20086","type":"Dubbo"},{"id":"12","name":"175.32.30.96:12345","type":"Dubbo"},{"id":"13","name":"175.32.30.97:12345","type":"Dubbo"},{"id":"14","name":"175.32.39.99:20086","type":"Dubbo"},{"id":"15","name":"175.32.39.41:20086","type":"Dubbo"},{"id":"16","name":"messageservice-sync.wcf.corp.tujia.com:80","type":"HttpClient"},{"id":"17","name":"175.32.39.82:20086","type":"Dubbo"},{"id":"18","name":"175.32.39.110:20086","type":"Dubbo"},{"id":"21","name":"175.32.39.100:20086","type":"Dubbo"},{"id":"31","name":"175.32.81.239:20086","type":"Dubbo"},{"id":"33","name":"175.32.82.87:20086","type":"Dubbo"},{"id":"34","name":"175.32.88.230:27021","type":"Redis"},{"id":"36","name":"175.32.86.170:12345","type":"Dubbo"},{"id":"-35","name":"175.32.82.88:20086","type":"Dubbo"},{"id":"-34","name":"175.32.86.230:27020","type":"Redis"},{"id":"-29","name":"175.32.82.103:12345","type":"Dubbo"},{"id":"-13","name":"175.32.30.131:20880","type":"Dubbo"},{"id":"6","name":"175.32.39.112:20086","type":"Dubbo"},{"id":"20","name":"175.32.39.81:20086","type":"Dubbo"},{"id":"24","name":"abtest.corp.tujia.com:80","type":"HttpClient"},{"id":"41","name":"175.32.88.230:27020","type":"Redis"},{"id":"-42","name":"175.32.82.104:12345","type":"Dubbo"},{"id":"-36","name":"175.32.86.172:12345","type":"Dubbo"},{"id":"-33","name":"175.32.86.148:20081","type":"Dubbo"},{"id":"-16","name":"175.32.39.179:20880","type":"Dubbo"},{"id":"30","name":"175.32.86.142:20880","type":"Dubbo"},{"id":"39","name":"175.32.81.238:20086","type":"Dubbo"},{"id":"40","name":"175.32.86.171:12345","type":"Dubbo"},{"id":"42","name":"175.32.82.124:20086","type":"Dubbo"},{"id":"32","name":"175.32.86.149:20081","type":"Unknown"},{"id":"-40","name":"175.32.86.108:20086","type":"Dubbo"},{"id":"22","name":"175.32.39.101:29995","type":"Dubbo"},{"id":"35","name":"175.32.82.65:20086","type":"Dubbo"},{"id":"-38","name":"175.32.82.123:20086","type":"Dubbo"},{"id":"27","name":"175.32.39.44:29995","type":"Dubbo"},{"id":"-14","name":"175.32.30.18:29995","type":"Dubbo"},{"id":"38","name":"175.32.82.125:20086","type":"Dubbo"},{"id":"-41","name":"175.32.86.196:20880","type":"Unknown"},{"id":"-37","name":"175.32.82.66:20086","type":"Dubbo"},{"id":"-27","name":"175.32.39.45:29995","type":"Dubbo"},{"id":"-22","name":"175.32.30.100:20081","type":"Unknown"},{"id":"25","name":"175.32.39.102:29995","type":"Dubbo"},{"id":"-24","name":"175.32.30.19:29995","type":"Dubbo"},{"id":"26","name":"175.32.30.101:20081","type":"Unknown"},{"id":"-44","name":"175.32.82.69:29995","type":"Unknown"},{"id":"-43","name":"175.32.82.67:29995","type":"Unknown"},{"id":"-39","name":"175.32.82.68:29995","type":"Unknown"},{"id":"28","name":"175.32.39.46:29995","type":"Dubbo"},{"id":"37","name":"175.32.82.147:20880","type":"Unknown"},{"id":"43","name":"175.32.86.168:20081","type":"Unknown"},{"id":"-25","name":"175.32.30.17:29995","type":"Unknown"},{"id":"44","name":"175.32.86.167:20081","type":"Unknown"},{"id":"23","name":"portalservice-sync.wcf.corp.tujia.com:80","type":"HttpClient"},{"id":"1","name":"User","type":"USER"}],"calls":[{"source":"-1","target":"-32","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":3},{"source":"-1","target":"-21","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":2},{"source":"-1","target":"-20","isAlert":false,"callType":"Dubbo","cpm":5,"avgResponseTime":5},{"source":"-1","target":"-126","isAlert":false,"callType":"Dubbo","cpm":4,"avgResponseTime":6},{"source":"-1","target":"-18","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":5},{"source":"-1","target":"-17","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":14},{"source":"-1","target":"-15","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":6},{"source":"-1","target":"-12","isAlert":false,"callType":"Dubbo","cpm":4,"avgResponseTime":3},{"source":"-1","target":"-11","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":2},{"source":"-1","target":"-126","isAlert":false,"callType":"Dubbo","cpm":5,"avgResponseTime":5},{"source":"-1","target":"-9","isAlert":false,"callType":"Dubbo","cpm":6,"avgResponseTime":2},{"source":"-1","target":"-8","isAlert":false,"callType":"Dubbo","cpm":8,"avgResponseTime":2},{"source":"-1","target":"-7","isAlert":false,"callType":"Jedis","cpm":21,"avgResponseTime":0},{"source":"-1","target":"53","isAlert":false,"callType":"Dubbo","cpm":8,"avgResponseTime":2},{"source":"-1","target":"-5","isAlert":false,"callType":"HttpClient","cpm":10,"avgResponseTime":44},{"source":"-1","target":"-4","isAlert":false,"callType":"HttpClient","cpm":5,"avgResponseTime":23},{"source":"-1","target":"-3","isAlert":false,"callType":"Dubbo","cpm":10,"avgResponseTime":4},{"source":"-1","target":"-2","isAlert":false,"callType":"HttpClient","cpm":9,"avgResponseTime":6},{"source":"-1","target":"2","isAlert":false,"callType":"Dubbo","cpm":7,"avgResponseTime":2},{"source":"-1","target":"3","isAlert":false,"callType":"HttpClient","cpm":51,"avgResponseTime":5},{"source":"-1","target":"4","isAlert":false,"callType":"HttpClient","cpm":38,"avgResponseTime":51},{"source":"-1","target":"5","isAlert":false,"callType":"Dubbo","cpm":4,"avgResponseTime":3},{"source":"-1","target":"7","isAlert":false,"callType":"Jedis","cpm":27,"avgResponseTime":0},{"source":"-1","target":"8","isAlert":false,"callType":"Jedis","cpm":23,"avgResponseTime":0},{"source":"-1","target":"62","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":10},{"source":"-1","target":"10","isAlert":false,"callType":"Dubbo","cpm":10,"avgResponseTime":19},{"source":"-1","target":"11","isAlert":false,"callType":"Dubbo","cpm":11,"avgResponseTime":4},{"source":"-1","target":"12","isAlert":false,"callType":"Dubbo","cpm":7,"avgResponseTime":2},{"source":"-1","target":"13","isAlert":false,"callType":"Dubbo","cpm":7,"avgResponseTime":2},{"source":"-1","target":"14","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":5},{"source":"-1","target":"15","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":5},{"source":"-1","target":"16","isAlert":false,"callType":"HttpClient","cpm":6,"avgResponseTime":21},{"source":"-1","target":"17","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":12},{"source":"-1","target":"18","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":10},{"source":"-1","target":"-126","isAlert":false,"callType":"Dubbo","cpm":5,"avgResponseTime":5},{"source":"-1","target":"21","isAlert":false,"callType":"Dubbo","cpm":4,"avgResponseTime":5},{"source":"-1","target":"31","isAlert":false,"callType":"Dubbo","cpm":4,"avgResponseTime":10},{"source":"-1","target":"33","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":11},{"source":"-1","target":"34","isAlert":false,"callType":"Jedis","cpm":7,"avgResponseTime":0},{"source":"-1","target":"36","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":2},{"source":"-1","target":"-35","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":11},{"source":"-1","target":"-34","isAlert":false,"callType":"Jedis","cpm":10,"avgResponseTime":0},{"source":"-1","target":"-29","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":3},{"source":"-1","target":"-13","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":52},{"source":"-1","target":"6","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":11},{"source":"-1","target":"20","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":11},{"source":"-1","target":"24","isAlert":false,"callType":"HttpClient","cpm":3,"avgResponseTime":5},{"source":"-1","target":"41","isAlert":false,"callType":"Jedis","cpm":8,"avgResponseTime":0},{"source":"-1","target":"-42","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":2},{"source":"-1","target":"-36","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":2},{"source":"-1","target":"-33","isAlert":false,"callType":"Dubbo","cpm":3,"avgResponseTime":3},{"source":"-1","target":"-16","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":44},{"source":"-1","target":"30","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":19},{"source":"-1","target":"39","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":9},{"source":"-1","target":"40","isAlert":false,"callType":"Dubbo","cpm":2,"avgResponseTime":2},{"source":"-1","target":"42","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":4},{"source":"-1","target":"-126","isAlert":false,"callType":"","cpm":2,"avgResponseTime":4},{"source":"-1","target":"-126","isAlert":false,"callType":"","cpm":2,"avgResponseTime":4},{"source":"-1","target":"32","isAlert":false,"callType":"","cpm":1,"avgResponseTime":3},{"source":"-1","target":"-40","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":4},{"source":"-1","target":"22","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":5},{"source":"-1","target":"35","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":5},{"source":"-1","target":"-38","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":5},{"source":"-1","target":"27","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":5},{"source":"-1","target":"-14","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":7},{"source":"-1","target":"38","isAlert":false,"callType":"Dubbo","cpm":1,"avgResponseTime":5},{"source":"-1","target":"-41","isAlert":false,"callType":"","cpm":0,"avgResponseTime":61},{"source":"-1","target":"-37","isAlert":false,"callType":"Dubbo","cpm":0,"avgResponseTime":5},{"source":"-1","target":"-27","isAlert":false,"callType":"Dubbo","cpm":0,"avgResponseTime":6},{"source":"-1","target":"-22","isAlert":false,"callType":"","cpm":1,"avgResponseTime":4},{"source":"-1","target":"25","isAlert":false,"callType":"Dubbo","cpm":0,"avgResponseTime":6},{"source":"-1","target":"-24","isAlert":false,"callType":"Dubbo","cpm":0,"avgResponseTime":6},{"source":"-1","target":"26","isAlert":false,"callType":"","cpm":0,"avgResponseTime":4},{"source":"-1","target":"-44","isAlert":false,"callType":"","cpm":0,"avgResponseTime":6},{"source":"-1","target":"-43","isAlert":false,"callType":"","cpm":0,"avgResponseTime":5},{"source":"-1","target":"-39","isAlert":false,"callType":"","cpm":0,"avgResponseTime":7},{"source":"-1","target":"28","isAlert":false,"callType":"Dubbo","cpm":0,"avgResponseTime":6},{"source":"-1","target":"37","isAlert":false,"callType":"","cpm":0,"avgResponseTime":60},{"source":"-1","target":"43","isAlert":false,"callType":"","cpm":0,"avgResponseTime":4},{"source":"-1","target":"-25","isAlert":false,"callType":"","cpm":0,"avgResponseTime":7},{"source":"-1","target":"44","isAlert":false,"callType":"","cpm":0,"avgResponseTime":4},{"source":"-1","target":"104","isAlert":false,"callType":"","cpm":0,"avgResponseTime":20},{"source":"-1","target":"23","isAlert":false,"callType":"HttpClient","cpm":0,"avgResponseTime":93},{"source":"-1","target":"104","isAlert":false,"callType":"","cpm":0,"avgResponseTime":15},{"source":"1","target":"-1","isAlert":false,"callType":"","cpm":105,"avgResponseTime":78}]}}}

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Yuanxiangz** [comment] 2018-10-31 10:31
another error: http://skywalking.corp.tujia.com/img/node/UNKNOWN.png. but it's not the root cause of the above issue.

**Comment by hanahmily** [comment] 2018-11-09 09:20
@Yuanxiangz sorry for late. if `UNKNOWN.png` didn't exist, the `cytoscape.js` can render the whole graph. In short, `UNKNOWN.png` is the root cause.

v6 fixing this issue will be released next week.

**Comment by wu-sheng** [comment] 2018-11-09 12:21
Then @Yuanxiangz You could choose to add this image to avoid render failure, or simply use our 6.0.0-alpha release.

**Closed by wu-sheng** 2018-11-09 12:21 UTC
Labels: UI, bug

**Comment by Yuanxiangz** [comment] 2018-11-10 15:29
@hanahmily  the unknown.png error is always existed while the 'drawimage' error happened occasionally. that's why i said unknown.png error is not the root cause   @wu-sheng i will try 6.0.0 UI and update the result then.

**Comment by wu-sheng** [comment] 2018-11-10 15:30
Thanks. We have fixed this in 6
