### ISSUE TITLE
Over 100 instances of HystrixRequestVariable are being stored. This is likely the sign of a memory leak caused by using unique instances of HystrixConcurrencyStrategy instead of a single instance.

### ISSUE THREAD

**Issue by chenpengfei** [apache/incubator-skywalking#1604] opened 2018-08-29 13:12 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ * ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

5.0.0-RC-SNAPSHOT

- Which company or project?

[chehejia](https://www.chehejia.com/)

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

app print log info: Over 100 instances of HystrixRequestVariable are being stored. This is likely the sign of a memory leak caused by using unique instances of HystrixConcurrencyStrategy instead of a single instance.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-08-29 13:19
Could you provide a PR to us for fixing this?

**Comment by wu-sheng** [comment] 2018-08-29 13:20
> caused by using unique instances of HystrixConcurrencyStrategy instead of a single instance.

I am confused by this. Caused by singleton or no-singleton?

**Comment by wu-sheng** [comment] 2018-09-19 15:33
#1610 fixed, and already released in 5.0.0-RC2

**Closed by wu-sheng** 2018-09-19 15:33 UTC
Labels: agent, bug
