### ISSUE TITLE
 java.lang.AbstractMethodError: oracle.jdbc.driver.T4CPreparedStatement.unwrap

### ISSUE THREAD

**Issue by aiqing2171** [apache/incubator-skywalking#769] opened 2018-01-19 09:53 UTC
> Bug：
can not run my application when using skywalking-agent.

- Which version of SkyWalking, OS and JRE?
   win7, skywalking3.2.6, jre1.8. 
   mybatis 3.2.6, mybatis.spring.version1.2.2
   ojdbc14.version 10.2.0.3.0

- What happen?
When i started my application(start main method, it will start ClassPathXmlApplicationContext), i got this and the application stopped.

> Exception

 in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name ...: Invocation of init method failed; nested exception is java.lang.AbstractMethodError: oracle.jdbc.driver.T4CPreparedStatement.unwrap(Ljava/lang/Class;)Ljava/lang/Object;
	at
 org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:396)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1507)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:638)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at ********.main(ApplicationBootStrap.java:15)
Caused by: java.lang.AbstractMethodError: oracle.jdbc.driver.T4CPreparedStatement.unwrap(Ljava/lang/Class;)Ljava/lang/Object;
	at org.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement.unwrap(SWPreparedStatement.java:303)
	at com.alibaba.druid.filter.FilterChainImpl.unwrap(FilterChainImpl.java:137)
	at com.alibaba.druid.filter.FilterAdapter.unwrap(FilterAdapter.java:2643)
	at com.alibaba.druid.filter.FilterChainImpl.unwrap(FilterChainImpl.java:125)
	at com.alibaba.druid.filter.FilterAdapter.unwrap(FilterAdapter.java:2643)
	at com.alibaba.druid.filter.FilterChainImpl.unwrap(FilterChainImpl.java:125)
	at com.alibaba.druid.proxy.jdbc.WrapperProxyImpl.unwrap(WrapperProxyImpl.java:75)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.unwrap(StatementProxyImpl.java:559)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.unwrap(PreparedStatementProxyImpl.java:616)
	at com.alibaba.druid.util.OracleUtils.unwrapInternal(OracleUtils.java:88)
	at com.alibaba.druid.util.OracleUtils.enterImplicitCache(OracleUtils.java:63)
	at com.alibaba.druid.pool.PreparedStatementPool.put(PreparedStatementPool.java:91)
	at com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:172)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:85)
	at com.sun.proxy.$Proxy34.close(Unknown Source)
	at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:239)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy31.getNextValBySequenceName(Unknown Source)
	at com.**********.setMaxValue(******ComponentImpl.java:210)
	at com.**********.updateNextValue(******ComponentImpl.java:126)
	at com.**********.init(*****ComponentImpl.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:344)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:295)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:130)
	... 14 more

**Comment by ascrutae** [comment] 2018-01-25 08:56
Can you give me a demo for reproduce this issue? 

Still I have one question about this issue, Does the demo works without Skywalking agent? because I found that the method cannot found in the class `T4CPreparedStatement` but the Druid framework use the `unwrap` method  to execute some stuff.

**Comment by wu-sheng** [comment] 2018-01-26 04:50
@aiqing2171 I think you should provide us a demo to let us find out what is really going on.

**Comment by ascrutae** [comment] 2018-02-01 01:00
The PR had been merged, close this issue

**Closed** 2018-02-01 01:01 UTC
Labels: bug, duplicate
