### ISSUE TITLE
Dashboard to Service page Error

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1250] opened 2018-05-21 09:33 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta
request dashbord
```
http://localhost:8000/api/dashboard
```
response
```
{"data":{"getClusterBrief":{"numOfApplication":2,"numOfService":3,"numOfDatabase":1,"numOfCache":0,"numOfMQ":0},"getAlarmTrend":{"numOfAlarmRate":[0,0,0,0,3333,0,0,0,0,3333,0,0,0,0,0,0]},"getThermodynamic":{"nodes":[[0,0,0],[0,1,0],[0,2,0],[0,3,0],[0,4,0],[0,5,0],[0,6,0],[0,7,0],[0,8,0],[0,9,0],[0,10,0],[0,11,0],[0,12,0],[0,13,0],[0,14,0],[0,15,0],[0,16,0],[0,17,0],[0,18,0],[0,19,0],[0,20,0],[0,21,0],[0,22,0],[0,23,0],[0,24,0],[0,25,0],[0,26,0],[0,27,0],[0,28,0],[0,29,0],[0,30,0],[0,31,0],[0,32,0],[0,33,0],[0,34,0],[0,35,0],[0,36,0],[0,37,0],[0,38,0],[0,39,0],[0,40,0],[1,0,0],[1,1,0],[1,2,0],[1,3,0],[1,4,0],[1,5,0],[1,6,0],[1,7,0],[1,8,0],[1,9,0],[1,10,0],[1,11,0],[1,12,0],[1,13,0],[1,14,0],[1,15,0],[1,16,0],[1,17,0],[1,18,0],[1,19,0],[1,20,0],[1,21,0],[1,22,0],[1,23,0],[1,24,0],[1,25,0],[1,26,0],[1,27,0],[1,28,0],[1,29,0],[1,30,0],[1,31,0],[1,32,0],[1,33,0],[1,34,0],[1,35,0],[1,36,0],[1,37,0],[1,38,0],[1,39,0],[1,40,0],[2,0,0],[2,1,0],[2,2,0],[2,3,0],[2,4,0],[2,5,0],[2,6,0],[2,7,0],[2,8,0],[2,9,0],[2,10,0],[2,11,0],[2,12,0],[2,13,0],[2,14,0],[2,15,0],[2,16,0],[2,17,0],[2,18,0],[2,19,0],[2,20,0],[2,21,0],[2,22,0],[2,23,0],[2,24,0],[2,25,0],[2,26,0],[2,27,0],[2,28,0],[2,29,0],[2,30,0],[2,31,0],[2,32,0],[2,33,0],[2,34,0],[2,35,0],[2,36,0],[2,37,0],[2,38,0],[2,39,0],[2,40,0],[3,0,0],[3,1,0],[3,2,0],[3,3,0],[3,4,0],[3,5,0],[3,6,0],[3,7,0],[3,8,0],[3,9,0],[3,10,0],[3,11,0],[3,12,0],[3,13,0],[3,14,0],[3,15,0],[3,16,0],[3,17,0],[3,18,0],[3,19,0],[3,20,0],[3,21,0],[3,22,0],[3,23,0],[3,24,0],[3,25,0],[3,26,0],[3,27,0],[3,28,0],[3,29,0],[3,30,0],[3,31,0],[3,32,0],[3,33,0],[3,34,0],[3,35,0],[3,36,0],[3,37,0],[3,38,0],[3,39,0],[3,40,0],[4,0,5],[4,1,0],[4,2,0],[4,3,0],[4,4,0],[4,5,0],[4,6,0],[4,7,0],[4,8,0],[4,9,0],[4,10,0],[4,11,0],[4,12,0],[4,13,0],[4,14,0],[4,15,0],[4,16,0],[4,17,0],[4,18,0],[4,19,0],[4,20,0],[4,21,0],[4,22,0],[4,23,0],[4,24,0],[4,25,0],[4,26,0],[4,27,0],[4,28,0],[4,29,0],[4,30,0],[4,31,0],[4,32,0],[4,33,0],[4,34,0],[4,35,0],[4,36,0],[4,37,0],[4,38,0],[4,39,0],[4,40,0],[5,0,0],[5,1,0],[5,2,0],[5,3,0],[5,4,0],[5,5,0],[5,6,0],[5,7,0],[5,8,0],[5,9,0],[5,10,0],[5,11,0],[5,12,0],[5,13,0],[5,14,0],[5,15,0],[5,16,0],[5,17,0],[5,18,0],[5,19,0],[5,20,0],[5,21,0],[5,22,0],[5,23,0],[5,24,0],[5,25,0],[5,26,0],[5,27,0],[5,28,0],[5,29,0],[5,30,0],[5,31,0],[5,32,0],[5,33,0],[5,34,0],[5,35,0],[5,36,0],[5,37,0],[5,38,0],[5,39,0],[5,40,0],[6,0,0],[6,1,0],[6,2,0],[6,3,0],[6,4,0],[6,5,0],[6,6,0],[6,7,0],[6,8,0],[6,9,0],[6,10,0],[6,11,0],[6,12,0],[6,13,0],[6,14,0],[6,15,0],[6,16,0],[6,17,0],[6,18,0],[6,19,0],[6,20,0],[6,21,0],[6,22,0],[6,23,0],[6,24,0],[6,25,0],[6,26,0],[6,27,0],[6,28,0],[6,29,0],[6,30,0],[6,31,0],[6,32,0],[6,33,0],[6,34,0],[6,35,0],[6,36,0],[6,37,0],[6,38,0],[6,39,0],[6,40,0],[7,0,0],[7,1,0],[7,2,0],[7,3,0],[7,4,0],[7,5,0],[7,6,0],[7,7,0],[7,8,0],[7,9,0],[7,10,0],[7,11,0],[7,12,0],[7,13,0],[7,14,0],[7,15,0],[7,16,0],[7,17,0],[7,18,0],[7,19,0],[7,20,0],[7,21,0],[7,22,0],[7,23,0],[7,24,0],[7,25,0],[7,26,0],[7,27,0],[7,28,0],[7,29,0],[7,30,0],[7,31,0],[7,32,0],[7,33,0],[7,34,0],[7,35,0],[7,36,0],[7,37,0],[7,38,0],[7,39,0],[7,40,0],[8,0,0],[8,1,0],[8,2,0],[8,3,1],[8,4,0],[8,5,0],[8,6,0],[8,7,0],[8,8,0],[8,9,0],[8,10,0],[8,11,0],[8,12,0],[8,13,0],[8,14,0],[8,15,0],[8,16,0],[8,17,0],[8,18,0],[8,19,0],[8,20,0],[8,21,0],[8,22,0],[8,23,0],[8,24,0],[8,25,0],[8,26,0],[8,27,0],[8,28,0],[8,29,0],[8,30,0],[8,31,0],[8,32,0],[8,33,0],[8,34,0],[8,35,0],[8,36,0],[8,37,0],[8,38,0],[8,39,0],[8,40,0],[9,0,0],[9,1,0],[9,2,0],[9,3,1],[9,4,0],[9,5,0],[9,6,1],[9,7,0],[9,8,0],[9,9,0],[9,10,0],[9,11,0],[9,12,0],[9,13,0],[9,14,0],[9,15,0],[9,16,0],[9,17,0],[9,18,0],[9,19,0],[9,20,0],[9,21,0],[9,22,0],[9,23,0],[9,24,0],[9,25,0],[9,26,0],[9,27,0],[9,28,0],[9,29,0],[9,30,0],[9,31,0],[9,32,0],[9,33,0],[9,34,0],[9,35,0],[9,36,0],[9,37,0],[9,38,0],[9,39,0],[9,40,0],[10,0,0],[10,1,0],[10,2,0],[10,3,0],[10,4,0],[10,5,0],[10,6,0],[10,7,0],[10,8,0],[10,9,0],[10,10,0],[10,11,0],[10,12,0],[10,13,0],[10,14,0],[10,15,0],[10,16,0],[10,17,0],[10,18,0],[10,19,0],[10,20,0],[10,21,0],[10,22,0],[10,23,0],[10,24,0],[10,25,0],[10,26,0],[10,27,0],[10,28,0],[10,29,0],[10,30,0],[10,31,0],[10,32,0],[10,33,0],[10,34,0],[10,35,0],[10,36,0],[10,37,0],[10,38,0],[10,39,0],[10,40,0],[11,0,0],[11,1,0],[11,2,0],[11,3,0],[11,4,0],[11,5,0],[11,6,0],[11,7,0],[11,8,0],[11,9,0],[11,10,0],[11,11,0],[11,12,0],[11,13,0],[11,14,0],[11,15,0],[11,16,0],[11,17,0],[11,18,0],[11,19,0],[11,20,0],[11,21,0],[11,22,0],[11,23,0],[11,24,0],[11,25,0],[11,26,0],[11,27,0],[11,28,0],[11,29,0],[11,30,0],[11,31,0],[11,32,0],[11,33,0],[11,34,0],[11,35,0],[11,36,0],[11,37,0],[11,38,0],[11,39,0],[11,40,0],[12,0,0],[12,1,0],[12,2,0],[12,3,0],[12,4,0],[12,5,0],[12,6,0],[12,7,0],[12,8,0],[12,9,0],[12,10,0],[12,11,0],[12,12,0],[12,13,0],[12,14,0],[12,15,0],[12,16,0],[12,17,0],[12,18,0],[12,19,0],[12,20,0],[12,21,0],[12,22,0],[12,23,0],[12,24,0],[12,25,0],[12,26,0],[12,27,0],[12,28,0],[12,29,0],[12,30,0],[12,31,0],[12,32,0],[12,33,0],[12,34,0],[12,35,0],[12,36,0],[12,37,0],[12,38,0],[12,39,0],[12,40,0],[13,0,0],[13,1,0],[13,2,0],[13,3,0],[13,4,0],[13,5,0],[13,6,0],[13,7,0],[13,8,0],[13,9,0],[13,10,0],[13,11,0],[13,12,0],[13,13,0],[13,14,0],[13,15,0],[13,16,0],[13,17,0],[13,18,0],[13,19,0],[13,20,0],[13,21,0],[13,22,0],[13,23,0],[13,24,0],[13,25,0],[13,26,0],[13,27,0],[13,28,0],[13,29,0],[13,30,0],[13,31,0],[13,32,0],[13,33,0],[13,34,0],[13,35,0],[13,36,0],[13,37,0],[13,38,0],[13,39,0],[13,40,0],[14,0,0],[14,1,0],[14,2,0],[14,3,0],[14,4,0],[14,5,0],[14,6,0],[14,7,0],[14,8,0],[14,9,0],[14,10,0],[14,11,0],[14,12,0],[14,13,0],[14,14,0],[14,15,0],[14,16,0],[14,17,0],[14,18,0],[14,19,0],[14,20,0],[14,21,0],[14,22,0],[14,23,0],[14,24,0],[14,25,0],[14,26,0],[14,27,0],[14,28,0],[14,29,0],[14,30,0],[14,31,0],[14,32,0],[14,33,0],[14,34,0],[14,35,0],[14,36,0],[14,37,0],[14,38,0],[14,39,0],[14,40,0],[15,0,0],[15,1,0],[15,2,0],[15,3,0],[15,4,0],[15,5,0],[15,6,0],[15,7,0],[15,8,0],[15,9,0],[15,10,0],[15,11,0],[15,12,0],[15,13,0],[15,14,0],[15,15,0],[15,16,0],[15,17,0],[15,18,0],[15,19,0],[15,20,0],[15,21,0],[15,22,0],[15,23,0],[15,24,0],[15,25,0],[15,26,0],[15,27,0],[15,28,0],[15,29,0],[15,30,0],[15,31,0],[15,32,0],[15,33,0],[15,34,0],[15,35,0],[15,36,0],[15,37,0],[15,38,0],[15,39,0],[15,40,0]],"responseTimeStep":50},"getTopNSlowService":[{"key":"4","label":"/wolverine/services","value":10112},{"key":"-3","label":"/wolverine/services","value":2285}],"getTopNApplicationThroughput":[{"key":-1,"label":"lightning-netty","value":0},{"key":2,"label":"wolverine-backend","value":0}]}}
```

![image](https://user-images.githubusercontent.com/11530760/40300847-034c2b44-5d1d-11e8-965c-d269f11b91ad.png)

occur error

![image](https://user-images.githubusercontent.com/11530760/40300867-144a635c-5d1d-11e8-8c2b-bba65c14b37b.png)

in service page:
```
http://localhost:8000/api/service
```
param
```
{"variables":{"duration":{"start":"2018-05-22 1341","end":"2018-05-22 1356","step":"MINUTE"},"serviceId":"-10"},"query":"\n  query Service($serviceId: ID!, $duration: Duration!) {\n    getServiceResponseTimeTrend(serviceId: $serviceId, duration: $duration) {\n      trendList\n    }\n    getServiceThroughputTrend(serviceId: $serviceId, duration: $duration) {\n      trendList\n    }\n    getServiceSLATrend(serviceId: $serviceId, duration: $duration) {\n      trendList\n    }\n    getServiceTopology(serviceId: $serviceId, duration: $duration) {\n      nodes {\n        id\n        name\n        type\n        ... on ServiceNode {\n          sla\n          calls\n          numOfServiceAlarm\n        }\n      }\n      calls {\n        source\n        target\n        isAlert\n        callType\n        cpm\n        avgResponseTime\n      }\n    }\n  }\n"}
```
response
```json
{
    "data": {
        "getServiceResponseTimeTrend": {
            "trendList": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                15,
                22,
                14,
                13,
                20,
                19,
                41,
                59
            ]
        },
        "getServiceThroughputTrend": {
            "trendList": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                5,
                6,
                5,
                6,
                6,
                5,
                6,
                5
            ]
        },
        "getServiceSLATrend": {
            "trendList": [
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000,
                10000
            ]
        },
        "getServiceTopology": {
            "nodes": [
                {
                    "id": "-3",
                    "name": "/wolverine/services",
                    "sla": 10000,
                    "calls": 44,
                    "numOfServiceAlarm": 0
                },
                {
                    "id": "3",
                    "name": "/api/v1/services",
                    "sla": 10000,
                    "calls": 44,
                    "numOfServiceAlarm": 0
                },
                {
                    "id": "11",
                    "name": "Mysql/PreparedStatement/execute",
                    "sla": 10000,
                    "calls": 659,
                    "numOfServiceAlarm": 0
                }
            ],
            "calls": [
                {
                    "source": "36",
                    "target": "-3",
                    "isAlert": false,
                    "callType": "SpringMVC",
                    "cpm": 2,
                    "avgResponseTime": 26
                },
                {
                    "source": "44",
                    "target": "-3",
                    "isAlert": false,
                    "callType": "SpringMVC",
                    "cpm": 0,
                    "avgResponseTime": 7
                },
                {
                    "source": "-42",
                    "target": "-3",
                    "isAlert": false,
                    "callType": "SpringMVC",
                    "cpm": 0,
                    "avgResponseTime": 9
                },
                {
                    "source": "-3",
                    "target": "3",
                    "isAlert": false,
                    "callType": "SpringMVC",
                    "cpm": 2,
                    "avgResponseTime": 5
                },
                {
                    "source": "-3",
                    "target": "11",
                    "isAlert": false,
                    "callType": "SpringMVC",
                    "cpm": 6,
                    "avgResponseTime": 1
                }
            ]
        }
    }
}
```

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-05-21 09:47
@hanahmily some guess?

**Comment by candyleer** [comment] 2018-05-22 06:42
I read the ui codes,maybe it's caused by 
in `getServiceTopology ` the nodes don't contain the calls `source`,only `target`

**Comment by wu-sheng** [comment] 2018-05-22 07:00
> I read the ui codes,maybe it's caused by
in getServiceTopology the nodes don't contain the calls source,only target

If `nodes` doesn't include all `source` and `target`, that should a backend bug.

**Comment by candyleer** [comment] 2018-05-22 07:07
Yes ,I am reading the back method and try to fix it

**Comment by wu-sheng** [comment] 2018-05-22 07:29
I am a little confused. Local span should be not part of analysis, and if EntrySpan and ExistSpan are in different segment, then should no dependencies.

**Comment by candyleer** [comment] 2018-05-22 07:38
it seems the dependencies are come from 
```
serviceReferenceMetricUIDAO.getFrontServices(step, startTimeBucket, endTimeBucket, MetricSource.Callee, serviceId)
```
```
serviceReferenceMetricUIDAO.getBehindServices(step, startTimeBucket, endTimeBucket, MetricSource.Caller, serviceId)
```

**Comment by wu-sheng** [comment] 2018-05-22 07:46
That is query for front and behind, but, that should not be the problem.

**Comment by hanahmily** [comment] 2018-06-09 14:06
Duplicate of #1195.

**Closed by hanahmily** 2018-06-09 14:06 UTC
Labels: UI, bug
