### ISSUE TITLE
Exception :: InstMethodsInter : class[class com.mysql.jdbc.NonRegisteringDriver] after method[connect] intercept failure

### ISSUE THREAD

**Issue by ychandu** [apache/incubator-skywalking#1947] opened 2018-11-22 09:31 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X ] Question or discussion
- [ ] Bug
- [] Requirement
- [ ] Feature or performance improvement

___
### Question
- ERROR 2018-11-22 07:39:21:390 InstMethodsInter :  class[class com.mysql.jdbc.NonRegisteringDriver] after method[connect] intercept failure
java.lang.ClassCastException: com.sun.proxy.$Proxy93 cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
        at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
        at com.mysql.jdbc.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:430)
        at com.mysql.jdbc.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:170)
        at com.mysql.jdbc.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:85)
        at com.mysql.jdbc.NonRegisteringDriver.connectReplicationConnection(NonRegisteringDriver.java:457)
        at com.mysql.jdbc.NonRegisteringDriver.connect$original$i2EwiijI(NonRegisteringDriver.java:314)
        at com.mysql.jdbc.NonRegisteringDriver.connect$original$i2EwiijI$accessor$vTQvnzP9(NonRegisteringDriver.java)
        at com.mysql.jdbc.NonRegisteringDriver$auxiliary$6GDXOaKs.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
        at com.mysql.jdbc.Driver.connect$accessor$5Y4GCtgv(Driver.java)
        at com.mysql.jdbc.Driver$auxiliary$JfVgABkU.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)
        at com.mysql.jdbc.Driver.connect(Driver.java)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

I am getting the above class cast exception in my Javagent. with the latest skywalking 6- alpha release. Please let me know how to handle this exception other than upgrading in cp30 jar

**Comment by wu-sheng** [comment] 2018-11-22 09:47
This is a bug or uncovered instrumentation. 

![image](https://user-images.githubusercontent.com/5441976/48894786-8c2f4c00-ee7e-11e8-8699-f64bff5917d2.png)

Based on the source codes, `LoadBalancedConnectionProxy.createProxyInstance` will create proxy. SkyWalking agent needs to intercept this method result, and enhanced it.

**Comment by wu-sheng** [comment] 2018-11-22 09:50
This should be fixed in beta release. And you could easily remove mysql-plugin.jar in plugin folder and make other things work.

**Comment by ascrutae** [comment] 2018-11-27 13:09
This issue has been fix in PR #1961 , I had test it in `loadbalance` and `replication` mode.

**Comment by wu-sheng** [comment] 2018-11-27 13:11
@ychandu If you want to re-compile master codes to run, please make sure you use the new backend. Because the next release(beta) will make agent run under v2 protocol.

The backend is compatible with old agent, but new agent can't report data to old collector. Be carefule.

**Comment by wu-sheng** [comment] 2018-11-27 14:05
Fixed

**Closed by wu-sheng** 2018-11-27 14:05 UTC
Labels: agent, bug

**Comment by ychandu** [comment] 2018-12-01 19:53
Thanks you, i will check.

**Comment by Lokipy** [comment] 2019-02-01 09:41
- question
I also have this problem.
with the latest skywalking 6.0.0-beta，help。
`DEBUG 2019-02-01 17:14:22:533 AbstractClassEnhancePluginDefine :  prepare to enhance class com.mysql.jdbc.JDBC42PreparedStatement by org.apache.skywalking.apm.plugin.jdbc.mysql.define.PreparedStatementInstrumentation.
DEBUG 2019-02-01 17:14:22:533 AbstractClassEnhancePluginDefine :  enhance class com.mysql.jdbc.JDBC42PreparedStatement by org.apache.skywalking.apm.plugin.jdbc.mysql.define.PreparedStatementInstrumentation completely.
DEBUG 2019-02-01 17:14:22:533 SkyWalkingAgent :  Finish the prepare stage for com.mysql.jdbc.JDBC42PreparedStatement.
DEBUG 2019-02-01 17:14:22:571 SkyWalkingAgent :  On Transformation class com.mysql.jdbc.JDBC42PreparedStatement.
ERROR 2019-02-01 17:14:22:586 InstMethodsInter :  class[class com.mysql.jdbc.NonRegisteringDriver] after method[connect] intercept failure
java.lang.ClassCastException: com.sun.proxy.$Proxy121 cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance
        at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
        at com.mysql.jdbc.ReplicationConnectionProxy.initializeSlavesConnection(ReplicationConnectionProxy.java:444)
        at com.mysql.jdbc.ReplicationConnectionProxy.<init>(ReplicationConnectionProxy.java:170)
        at com.mysql.jdbc.ReplicationConnectionProxy.createProxyInstance(ReplicationConnectionProxy.java:85)
        at com.mysql.jdbc.NonRegisteringDriver.connectReplicationConnection(NonRegisteringDriver.java:459)
        at com.mysql.jdbc.NonRegisteringReplicationDriver.connect(NonRegisteringReplicationDriver.java:46)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:874)
        at com.mapletown.common.datamanager.druid.DruidAutoConfiguration.buildDataSource(DruidAutoConfiguration.java:72)
        at com.mapletown.common.datamanager.druid.DruidAutoConfiguration.dataSource(DruidAutoConfiguration.java:41)
        at com.mapletown.common.datamanager.druid.DruidAutoConfiguration$$EnhancerBySpringCGLIB$$51545aed.CGLIB$dataSource$0(<generated>)
        at com.mapletown.common.datamanager.druid.DruidAutoConfiguration$$EnhancerBySpringCGLIB$$51545aed$$FastClassBySpringCGLIB$$bb9649d4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
        at com.mapletown.common.datamanager.druid.DruidAutoConfiguration$$EnhancerBySpringCGLIB$$51545aed.dataSource(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1256)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1105)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:474)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1256)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1105)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
`

**Comment by wu-sheng** [comment] 2019-02-01 09:54
If you could provide a demo to reproduce the issue in 6 GA agent. We may could help.

**Comment by Lokipy** [comment] 2019-02-01 09:57
> If you could provide a demo to reproduce the issue in 6 GA agent. We may could help.

I also tested with 6 GA agent，it has the same question.

**Comment by wu-sheng** [comment] 2019-02-01 10:05
Then submit an issue with the demo codes. You could try to fix it.

**Comment by dsc6636926** [comment] 2019-02-12 04:08
> > If you could provide a demo to reproduce the issue in 6 GA agent. We may could help.
> 
> I also tested with 6 GA agent，it has the same question.

what's the version of mysql-connector?

i test it on version 5.1.41,then failed,because the method initializeMasterConnection use NonRegisteringDriver.connect,
![image](https://user-images.githubusercontent.com/7552492/52610941-28854f80-2ebe-11e9-9e76-e78697765c13.png)

 6 GA agent  intercept the method LoadBalancedConnectionProxy.createProxyInstance,
![image](https://user-images.githubusercontent.com/7552492/52611124-ec9eba00-2ebe-11e9-8e18-d7ea6e7c8e1c.png)

so it can work on mysql-connector 6.* and upper version but not work on 5.*

**Comment by wu-sheng** [comment] 2019-02-12 04:17
Look like need another interceptor for `driver.connect`, for supporting 5.x. @dsc6636926 Could you submit a pull request to fix this?

**Comment by dsc6636926** [comment] 2019-02-12 04:20
@wu-sheng ok,i will try
@Lokipy i think you can upgrade your mysql-connector version to 6.0.6 to make it work soon

**Comment by dsc6636926** [comment] 2019-02-12 07:35
i think we should create a new plugin to fix this， because the package "com.mysql.cj" is appeared since MySQL Connector/J 6.0, and to fix this issue i must add “com.mysql.jdbc.LoadBalancedConnectionProxy” to org.apache.skywalking.apm.plugin.jdbc.mysql.define.enhanceClass.
![image](https://user-images.githubusercontent.com/7552492/52619098-c6d3de00-2edb-11e9-894b-bc694e689c25.png)

but
the interceptorClass org.apache.skywalking.apm.plugin.jdbc.mysql.CreateLoadBalancedConnectionProxyInstanceInterceptor has imported "com.mysql.cj" class whitch is not appeared in MySQL Connector/J 5.x 
![image](https://user-images.githubusercontent.com/7552492/52618942-3a292000-2edb-11e9-8d38-d80f80147c8b.png)

**Comment by wu-sheng** [comment] 2019-02-12 15:01
Look like you want to create new instrument and interceptor, not a plugin. Am I right?

**Comment by wu-sheng** [comment] 2019-02-12 15:03
Plugin for mysql 6.x is good for me, just look like the mysql 5.x plugin is still worked in some cases. Please make sure the two would conflict with each other.
