### ISSUE TITLE
5.0.0-rc collector error Too many open files

### ISSUE THREAD

**Issue by zshi456** [apache/incubator-skywalking#1665] opened 2018-09-12 08:59 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
org.apache.skywalking.apm.collector.core.util.FileUtils -895529116 [pool-3-thread-1] ERROR [] - ../buffer/offset_20180830141734.sw (Too many open files)

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0-rc  
- Which company or project?
collector
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by zshi456** [comment] 2018-09-12 09:16
2018-09-09 23:02:41,120 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.OffsetManager -895514116 [pool-3-thread-1] ERROR [] - flush offset file in background failure.
java.lang.NullPointerException: null
2018-09-09 23:02:43,125 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader -895516121 [pool-4-thread-1] ERROR [] - Segment buffer pre read failure.
java.lang.NullPointerException: null
2018-09-09 23:02:44,120 - org.apache.skywalking.apm.collector.core.util.FileUtils -895517116 [pool-3-thread-1] ERROR [] - ../buffer/offset_20180830141734.sw (Too many open files)

**Comment by wu-sheng** [comment] 2018-09-12 09:26
Most likely, caused by this https://github.com/apache/incubator-skywalking/pull/1661

**Comment by zshi456** [comment] 2018-09-14 06:07
根据1661的pr修改后，句柄数没有明显的改善，还是很大

**Comment by wu-sheng** [comment] 2018-09-14 06:29
English please.

**Comment by wu-sheng** [comment] 2018-09-24 03:14
Still keep this open, no one reported this again. And can't pinpoint the leak right now.

**Comment by peng-yongsheng** [comment] 2018-11-24 02:37
@zshi456 First of all, say sorry about this issue. Some times ago, I've been coding the feature of the SkyWalking 6.0. Now, I will check this issue, maybe few days later, It will be fixed.

**Comment by peng-yongsheng** [comment] 2018-11-24 16:09
Really, I've startup the OAP server and mock a lot of trace into it,  the file handlers leaked.  

There are 479 files opened when OAP server startup. 
There are 499 file handlers hold by the process after I send 1000 trace into OAP server.

**Comment by peng-yongsheng** [comment] 2018-11-25 08:14
@zshi456 I've fixed this issue in 6.0 beta, you could copy my changed code to the 5.0 version, and package it yourself.

**Closed by peng-yongsheng** 2018-11-25 08:14 UTC
Labels: bug
