### ISSUE TITLE
Click on page service ， display blank

### ISSUE THREAD

**Issue by yrjjf** [apache/incubator-skywalking#1320] opened 2018-06-07 07:29 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

Click on page service ， display blank，Other page clicks can be displayed normally。Want to know what is the cause of it?
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0 beta 。centos7.2  JDK1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

When it was originally deployed, it could be clicked normally. But the number of services is relatively small. Now there are more than 150 statistics. I don't know if this is the reason.

The log is as follows:
2018-06-07 15:18:02,642 - org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler -78391585 [qtp1163157114-7013] INFO  [] - Execution result is ExecutionResultImpl{data={searchService=[{key=-6, label=10.253.100.174:9110.com.hsjry.p2p.userbiz.bill.facade.AccountSearchBillBizFacade.ifUserLoginIn(null)}, {key=9, label=10.253.100.174:9110.com.hsjry.p2p.userbiz.facade.AccountBasicSearchBizFacade.queryBindCardInfo(null)}, {key=-10, label=10.253.40.113:9101.com.hsjry.p2p.usercore.bill.facade.UserImBillFacade.queryUserImBillById(null)}, {key=-8, label=10.253.40.113:9101.com.hsjry.p2p.usercore.facade.UserBindCardFacade.queryBindCardInfo(null)}, {key=7, label=/notice/pullnotice.json}, {key=-15, label=10.139.32.71:9121.com.hsjry.p2p.trade.purchase.facade.service.PurchaseQueryFacade.QueryPurchaseCreditBank(null)}, {key=-12, label=10.253.100.174:9110.com.hsjry.p2p.userbiz.bill.facade.UserImInfoFacade.queryUserImInfo(null)}, {key=-14, label=/notice/pullnotice}, {key=-23, label=10.139.32.71:9121.com.hsjry.p2p.trade.purchase.facade.service.CommonQueryFacade.queryLastDealOrder(null)}, {key=19, label=10.253.100.174:9104.com.hsjry.p2p.platform.facade.HelpCenterFacade.queryHelpCenterTree(null)}]}, errors=[], dataPresent=true, extensions=null}
2018-06-07 15:18:02,687 - org.apache.skywalking.apm.collector.ui.jetty.handler.GraphQLHandler -78391630 [qtp1163157114-7115] INFO  [] - Execution result is ExecutionResultImpl{data={getServiceResponseTimeTrend={trendList=[3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 4]}, getServiceThroughputTrend={trendList=[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 73, 203, 2, 2, 2]}, getServiceSLATrend={trendList=[10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]}, getServiceTopology={nodes=[{id=-6, name=10.253.100.174:9110.com.hsjry.p2p.userbiz.bill.facade.AccountSearchBillBizFacade.ifUserLoginIn(null), type=null, sla=10000, calls=304, numOfServiceAlarm=0}, {id=6, name=Jedis/get, type=null, sla=10000, calls=304, numOfServiceAlarm=0}, {id=1, name=User, type=USER}], calls=[{source=7, target=-6, isAlert=false, callType=tiny-rpc, cpm=2, avgResponseTime=4}, {source=1, target=-6, isAlert=false, callType=tiny-rpc, cpm=17, avgResponseTime=3}, {source=-6, target=6, isAlert=false, callType=tiny-rpc, cpm=19, avgResponseTime=0}]}}, errors=[], dataPresent=true, extensions=null}

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-06-07 07:31
@hanamily You may can help about this. Maybe some invalid data.

**Comment by yrjjf** [comment] 2018-06-07 07:55
Just trying to reboot collectorService and webappService, It can be shown normally. In a few days, see if the same problem will happen again. Thank you！

**Comment by hanahmily** [comment] 2018-06-07 07:59
Duplicate of #141

**Closed by hanahmily** 2018-06-07 07:59 UTC
Labels: duplicate

**Comment by hanahmily** [comment] 2018-06-07 08:04
Sorry, Duplicate of https://github.com/apache/incubator-skywalking-ui/issues/141
