### ISSUE TITLE
something wrong  about zipkin-receiver

### ISSUE THREAD

**Issue by amoyf** [apache/incubator-skywalking#1495] opened 2018-07-25 07:20 UTC
- [ ] Question or discussion

___
### Question
- What do you want to know?
my skywalking version is beta2 n I open the function of ZipKin Receiver .I apply a zipkin-agent that used for php server in a php application.N Here is something wrong. N how can I solve the problem.Thank u!

I will give some message:

Here is the config file that I set in php server:
![phpmolten](https://user-images.githubusercontent.com/27755589/43185066-651bb9a6-901d-11e8-885d-51434f83071c.jpg)

Here is the message that collector.log showed:
![message](https://user-images.githubusercontent.com/27755589/43185072-6a14e0b8-901d-11e8-85a6-4a2a090ed2cd.jpg)

**Comment by wu-sheng** [comment] 2018-07-25 07:30
See https://github.com/apache/incubator-skywalking/pull/1420 . Fixed.

**Comment by amoyf** [comment] 2018-07-25 08:38
Hi,sir.I noticed that [https://github.com/apache/incubator-skywalking/pull/1420](#1420 ) .I found u have merge the fixed code into master.My SkyWalking Beta2 is compiled from 5.0.0-beta2 release.
N the releases that 5.0.0-beta2 is include the fixed code.
But I still could not solve the problem.Is there any help?

**Comment by wu-sheng** [comment] 2018-07-25 09:07
> But I still could not solve the problem.Is there any help?

There are two easy ways:
1. Package master codes
1. `Git Cherry-pick` the pull request commit to the tag head. Then recompile. I recommend this because it is safer.

**Comment by amoyf** [comment] 2018-07-26 02:31
@wu-sheng Hi,sir.I recompiled from tag 5.0.0-beta2 .But it showed some error message when I make PHP(molten,a php-agent for Zipkin ) test.
Here is the message from  skywalking-collector-server.log:
<img width="512" alt="default" src="https://user-images.githubusercontent.com/27755589/43238015-ea396600-90be-11e8-9d42-780539cb7138.png">


And here is another message which  use ZipKin Brave+Java agent in test:

<img width="512" alt="default" src="https://user-images.githubusercontent.com/27755589/43238025-f0444b3c-90be-11e8-94bf-031bacb294e5.png">

**Comment by wu-sheng** [comment] 2018-07-26 02:35
> I recompiled from tag 5.0.0-beta2

Have you `cherry-pick` the pr I pointed to you?

**Comment by amoyf** [comment] 2018-07-26 02:54
@wu-sheng I didn‘t do that.I use git checkout .

**Comment by wu-sheng** [comment] 2018-07-26 02:56
> I didn‘t do that.I use git checkout .

That recompile is meaningless. The tag is exactly the codes you downloaded. You need cherry-pick

**Comment by amoyf** [comment] 2018-07-26 03:01
@wu-sheng I try again，Thank U sir

**Comment by wu-sheng** [comment] 2018-07-26 08:51
> I try what u told me to do(use git cherry-pick).But the error message still show again .

That shouldn't. Are you sure you are using the latest codes about this? Honest, I am not quite sure about this. Do you have any Java programmer at your sides? Could you do some debug to output the data you received?

**Comment by Sef135** [comment] 2018-07-27 06:56
@wu-sheng  Hi ,  how should  I  debug to ouput of the data . I  am  sure I use the newest Zipkin . 
https://github.com/openzipkin/brave-webmvc-example   
webmvc4 
![image](https://user-images.githubusercontent.com/6898355/43306180-dc0f9a74-91ac-11e8-9c75-1890e6cf3e5c.png)

And I only change this .
Amorf   is my friend .
 Amorf是服务端人员 ，我负责java开发 。 你说要debug 一下，那么我应该修改哪里才能打印收到数据的日志？
还有我确定我用的是最新的zipkin  除了这个地址修改，其他地方我都没用动到Zipkin 示例代码

**Comment by wu-sheng** [comment] 2018-07-27 07:57
See `SpanProcessor` to check whether `#buffer` is right. The parser is powered by official zipkin lib. So shouldn't have problem.

FYI @adriancole if you have any clue, leave message here.

**Comment by adriancole** [comment] 2018-07-27 08:53
the error message has "binaryAnnotations" in it. That is v1 structure, so it should be the /api/v1/spans endpoint. Even better to make sure v2 json is sent. This is ensured if you use recent brave/recent zipkin-reporter

**Comment by adriancole** [comment] 2018-07-27 08:54
if using php, https://github.com/openzipkin/zipkin-php uses v2 format as well

**Comment by wu-sheng** [comment] 2018-07-27 10:15
@amoyf Then you may need Molten project's help. I am closing this again.

**Closed by wu-sheng** 2018-07-27 10:15 UTC
Labels: bug, collector

**Comment by Sef135** [comment] 2018-07-30 02:12
@wu-sheng @adriancole   I used https://github.com/openzipkin/brave-webmvc-example webMvc4 to upload data to server   , then it reported jsonformat error .  I used java  not  Php .

**Comment by adriancole** [comment] 2018-07-30 02:36
if you are using a recent commit of that, it should send json in v2 format by default. I will double-check now.

**Comment by adriancole** [comment] 2018-07-30 02:40
actually your molten config will not work with v2 endpoint. please change it to v1 https://github.com/chuan-yun/Molten/issues/93

**Comment by Sef135** [comment] 2018-07-30 02:50
ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project receiver-zipkin-provider: Failed during checkstyle execution: There are 21 errors reported by Checkstyle 6.11.2 with skywalking/checkStyle.xml ruleset. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project receiver-zipkin-provider: Failed during checkstyle execution
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed during checkstyle execution
    at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute (CheckstyleViolationCheckMojo.java:547)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.checkstyle.exec.CheckstyleExecutorException: There are 21 errors reported by Checkstyle 6.11.2 with skywalking/checkStyle.xml ruleset.
@wu-sheng   I modified the file  (SpanProcessor)you mentioned above to output the log , then  when I compiled  . The errors  occured.

**Comment by Sef135** [comment] 2018-07-30 09:16
![image](https://user-images.githubusercontent.com/6898355/43388539-06a46000-941c-11e8-89e3-687115d28751.png)

@wu-sheng    I exec the command "  mvn clean package -DskipTests "  in the root dictory . it occur  error . I used v5.0.0-beta2  version .   I cant't solve it .

**Comment by wu-sheng** [comment] 2018-07-30 09:22
I can't see your exact errors. Look like your network is not good. Try to open VPN, or replace `install --registry=https://registry.npmjs.org/` to taobao's mirror, which in `apm-webapp/pom.xml`.

**Comment by Sef135** [comment] 2018-07-30 09:50
@wu-sheng  I have changed the apm-webapp/pom.xml   .But the error still occur  . Also  I don't know  why the error info can't show .   
`mvn clean package -DskipTests` this is the code I used

**Comment by wu-sheng** [comment] 2018-07-30 09:51
Have you changed to new mirror address? This build failure is definitely caused by network problem.

**Comment by Sef135** [comment] 2018-07-30 09:54
![image](https://user-images.githubusercontent.com/6898355/43390750-89867d46-9421-11e8-8315-4e6745be1369.png)
 I have changged it , is that right?

**Comment by wu-sheng** [comment] 2018-07-30 09:58
Maybe you need to redo `git clone` from the beginning, I guess you have damaged files.

You may choose to use `mvn -x ....` to see what is really happening.

**Comment by Sef135** [comment] 2018-07-30 10:06
@wu-sheng   `mvn clean package -DskipTests -X `   
like this  ?  Is it upper case letter ‘X‘?
