### ISSUE TITLE
error occured when start  a project which dependence on dubbo 

### ISSUE THREAD

**Issue by flysqrlboy** [apache/incubator-skywalking#1546] opened 2018-08-14 10:13 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking : 5.0.0-beta2
dubbo: 2.7.0-SNAPSHORT
jre:jre8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

------Exception stracktrace as below ----

[14/08/18 05:56:30:030 CST] main ERROR extension.ExtensionLoader:  [DUBBO] fail to inject via method setSkyWalkingDynamicField of interface com.alibaba.dubbo.rpc.Filter: No qualifying bean of type 'java.lang.Object' available: expected single matching bean but found 11: demo-provider,com.alibaba.dubbo.config.RegistryConfig,dubbo,demoService,com.alibaba.dubbo.demo.DemoService,environment,systemProperties,systemEnvironment,messageSource,applicationEventMulticaster,lifecycleProcessor, dubbo version: , current host: 192.168.24.126
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'java.lang.Object' available: expected single matching bean but found 11: demo-provider,com.alibaba.dubbo.config.RegistryConfig,dubbo,demoService,com.alibaba.dubbo.demo.DemoService,environment,systemProperties,systemEnvironment,messageSource,applicationEventMulticaster,lifecycleProcessor
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1041)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1092)
	at com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory.getExtension(SpringExtensionFactory.java:67)
	at com.alibaba.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:521)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:497)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:309)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:193)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:172)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.buildInvokerChain(ProtocolFilterWrapper.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:100)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:57)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.exportLocal(ServiceConfig.java:536)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:486)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:358)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:317)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:216)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:123)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at com.alibaba.dubbo.demo.provider.Provider.main(Provider.java:27)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-08-14 10:50
We don't support snapshot version. Does any release version trigger this issue?

**Comment by wu-sheng** [comment] 2018-08-14 10:52
@ascrutae this issue stack is uncommon. Does this relate to spring compatible issue?

**Comment by ascrutae** [comment] 2018-08-14 21:35
It seems to be. and I found that The PR https://github.com/apache/incubator-skywalking/pull/1375 maybe had resolved this problem. Could you test it in the latest code?

**Comment by ascrutae** [comment] 2018-08-15 02:10
which the skywalking agent from, download from the official website or package by self？ @flysqrlboy  if the agent from the official website, could you give me the demo to me for reproduce this issue?

**Comment by wu-sheng** [comment] 2018-08-15 03:12
More important issue is, where is Dubbo `2.7.0-SNAPSHOT`? I just recheck the Apache mail list, dubbo 2.6.3 is still under release voting. There is impossible for existing 2.7.0 . For a development version, we are very hard to make sure it works or not, because their codes are not stable.

The only exception is, you are a committer or contributor of Apache 2.7.0, trying to solve some problem before release.

**Comment by flysqrlboy** [comment] 2018-08-15 03:43
It seems to be the dubbo SNAPSHORT VERSION 's problem,I try again to restart the demo project with dubbo 2.6.2. The problem gone.

**Comment by wu-sheng** [comment] 2018-08-15 03:45
Thanks for your feedback. I am closing this. Let's dubbo 2.7.0 release will not bring this issue back.

**Closed by wu-sheng** 2018-08-15 03:45 UTC
Labels: question
