### ISSUE TITLE
Spring cloud support error

### ISSUE THREAD

**Issue by eaglewa** [apache/incubator-skywalking#1312] opened 2018-06-05 10:59 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
   5.0.0-beta, linux, docker, jdk1.8
- Which company or project?

- What happen?
ERROR 2018-06-05 03:27:49 InstMethodsInter :  class[class org.springframework.aop.framework.DefaultAopProxyFactory] after method[hasNoUserSuppliedProxyInterfaces] intercept failure 
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at org.apache.skywalking.apm.plugin.spring.patch.CreateAopProxyInterceptor.afterMethod(CreateAopProxyInterceptor.java:47)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at org.springframework.aop.framework.DefaultAopProxyFactory.hasNoUserSuppliedProxyInterfaces(DefaultAopProxyFactory.java)
	at org.springframework.aop.framework.DefaultAopProxyFactory.createAopProxy(DefaultAopProxyFactory.java:51)
	at org.springframework.aop.framework.ProxyCreatorSupport.createAopProxy(ProxyCreatorSupport.java:105)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:97)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.getObject(BindableProxyFactory.java:197)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:163)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1178)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.baixing.ms.kms.KmsServiceApplication.main(KmsServiceApplication.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

ERROR 2018-06-05 03:27:49 InstMethodsInter :  class[class org.springframework.aop.framework.DefaultAopProxyFactory] after method[hasNoUserSuppliedProxyInterfaces] intercept failure 
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at org.apache.skywalking.apm.plugin.spring.patch.CreateAopProxyInterceptor.afterMethod(CreateAopProxyInterceptor.java:47)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:105)
	at org.springframework.aop.framework.DefaultAopProxyFactory.hasNoUserSuppliedProxyInterfaces(DefaultAopProxyFactory.java)
	at org.springframework.aop.framework.DefaultAopProxyFactory.createAopProxy(DefaultAopProxyFactory.java:51)
	at org.springframework.aop.framework.ProxyCreatorSupport.createAopProxy(ProxyCreatorSupport.java:105)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:97)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.getObject(BindableProxyFactory.java:197)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:163)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1178)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.baixing.ms.kms.KmsServiceApplication.main(KmsServiceApplication.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-06-05 14:04
@ascrutae this looks like a unsupported version. 

@eaglewa what is your spring springmvc version?

**Comment by eaglewa** [comment] 2018-06-06 01:41
spring boot 2.0.1

**Comment by wu-sheng** [comment] 2018-06-06 01:45
@ascrutae Have you tested Spring boot 2.x? Or do we have plugin to support?

**Comment by eaglewa** [comment] 2018-06-06 03:52
Springboot 1.5.13.RELEASE is also not supported

**Comment by xyydcoo** [comment] 2018-06-06 05:13
i have common error,but my skywalking has data

**Comment by eaglewa** [comment] 2018-06-06 05:16
this is my test demo
[app.jar.zip](https://github.com/apache/incubator-skywalking/files/2074858/app.jar.zip)

**Comment by ascrutae** [comment] 2018-06-12 23:05
@eaglewa @xyydcoo  I had test the demo with the latest agent. But it cannot reproduce this issue. Here is the screen snapshot about that demo:

Here is the **dashboard**:
![image](http://odqd22a3k.bkt.clouddn.com/WX20180613-065434@2x.png)
Here is the **topology**:
![image](http://odqd22a3k.bkt.clouddn.com/WX20180613-065446@2x.png)
Here is the **trace**:
![image](http://odqd22a3k.bkt.clouddn.com/WX20180613-065503@2x.png)

**Comment by xyydcoo** [comment] 2018-06-13 02:38
@ascrutae  my UI is ok, but agent throw a exception

**Comment by xyydcoo** [comment] 2018-06-13 02:43
@ascrutae  my issus is #989(closed) ,but  my data was cleared.

**Comment by wu-sheng** [comment] 2018-06-13 02:44
@ascrutae Could you recheck the agent log, please.

**Comment by ascrutae** [comment] 2018-06-13 03:19
I double check it. but I don't got any error messages on my agent log.

**Comment by wu-sheng** [comment] 2018-06-13 04:28
Then I am going to close this. If anyome could provide a demo to trigger the issue, we can work on that again.

**Closed by wu-sheng** 2018-06-13 04:28 UTC
Labels: question
