### ISSUE TITLE
Spring Controller Interceptor

### ISSUE THREAD

**Issue by IanCao** [apache/incubator-skywalking#1617] opened 2018-09-03 05:34 UTC
![image](https://user-images.githubusercontent.com/32847163/44969096-105bec80-af7e-11e8-825e-56d57fabc477.png)

![image](https://user-images.githubusercontent.com/32847163/44970156-dc36fa80-af82-11e8-9331-cb0c580c9f9f.png)

![image](https://user-images.githubusercontent.com/32847163/44970151-d3462900-af82-11e8-9326-40ac41084791.png)

When enhancing a Controller, GetBeanInterceptor put REQUEST_KEY_IN_RUNTIME_CONTEXT into RuntimeContext.
In AbstractMethodInterceptor, There is no RESPONSE_KEY_IN_RUNTIME_CONTEXT in RuntimeContext , so AbstractMethodInterceptor create a entryspan but not stop it.

**Comment by IanCao** [comment] 2018-09-03 06:15
btw spring-web version is 4.2.5.REALSE

**Comment by wu-sheng** [comment] 2018-09-03 06:51
@ascrutae I think you need to explain what is happening.

**Comment by ascrutae** [comment] 2018-09-03 06:56
Just for different version of spring framework.

**Comment by IanCao** [comment] 2018-09-03 07:11
and in some slow call... RuntimeContext contains  RESPONSE_KEY_IN_RUNTIME_CONTEXT, but no REQUEST_KEY_IN_RUNTIME_CONTEXT...so it cause NPE.

just see this log

![image](https://user-images.githubusercontent.com/32847163/44972381-8adf3900-af8b-11e8-86dd-f5df396b0f27.png)

**Comment by ascrutae** [comment] 2018-09-03 07:12
Could you send the demo to reproduce this issue?

**Comment by wu-sheng** [comment] 2018-09-03 07:13
After demo post, I will tag this as a bug, because look like it is.

**Comment by IanCao** [comment] 2018-09-05 01:48
i found my app has been enhanced by other JavaAgent. This Agent load firstly and sw agent secondly..in this load order, InvokeForRequestInterceptor can not work. but if  i change the load order.(sw first) it works...

**Comment by wu-sheng** [comment] 2018-09-05 03:12
> i found my app has been enhanced by other JavaAgent. sw agent firstly, other Agent load secondly ..in this load order, InvokeForRequestInterceptor can not work. but if i change the load order.(sw secondly) it works...

If there is two javaagents, it is hard to say. I doubt there is any compatible test between them.

So I am closing this issue. Considering this is not caused by our enhancement, just caused by conflict with 3rd party agent. If you can pinpoint the issue, and send PR, welcome.

**Closed by wu-sheng** 2018-09-05 03:12 UTC
Labels: question
