### ISSUE TITLE
[agent]java.lang.NullPointerException: null with apm-spring-annotation-plugin-6.0.0-GA.jar

### ISSUE THREAD

**Issue by vanlin** [apache/incubator-skywalking#2308] opened 2019-03-02 05:21 UTC
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking ver:  6.0 GA
ServiceComb ver: 1.1.0
JRE: 1.8

when I enabled apm-spring-annotation-plugin-6.0.0-GA.jar plugins and then I get NPE ! 

NPE cause:

```java
org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.setSchemaLoader 
```
method @Inject annotation missing ,  schemaLoader cannot inject.
av
##### disabled apm-spring-annotation-plugin-6.0.0-GA.jar

![image](https://user-images.githubusercontent.com/983627/53677602-a1254200-3ced-11e9-907c-05d6aaebdfde.png)

##### enabled apm-spring-annotation-plugin-6.0.0-GA.jar

![image](https://user-images.githubusercontent.com/983627/53677605-abdfd700-3ced-11e9-9b6d-168a0c2daf7c.png)

**Comment by wu-sheng** [comment] 2019-03-03 12:35
@candyleer Could you take a look at this? You should have many experiences with this kind of issue. :)

**Comment by candyleer** [comment] 2019-03-03 14:58
OK,No problem

**Comment by candyleer** [comment] 2019-03-04 01:48
@vanlin can you provide a demo to reproduce this issue?

**Comment by vanlin** [comment] 2019-03-04 14:59
hi @candyleer,   look this please: https://github.com/vanlin/servicecombtest

**Comment by candyleer** [comment] 2019-03-05 09:57
I found the reason, the spring plugin remove the annotation when enhance the method, let me think and fix the issue

**Comment by wu-sheng** [comment] 2019-03-06 00:24
Fixed. PR merged in to master.

**Closed by wu-sheng** 2019-03-06 00:24 UTC
Labels: bug
